### PR TITLE
add data sets with different distributions and spec for group by

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Relates to https://github.com/crate/crate/issues/11413

Added new data sets (1 million records each) with different distributions, generator and a new spec

Some other distributions are similar to exisiting, like binomial being discrete version of normal (could have actually dropped normal and used binomial but went with normal as it's possible to convert it to int )

tried some others - they are in general either bell-shaped like normal or look like exponential, we can add them of course but this is the minimal list of basic "shapes"

Poisson can be approximated to normal but with small loc it's right skewed - included it as well as it's another possible shape.

Plots generated by 
```

#plt.hist(np.random.normal(loc=0, scale=1e10, size=1000000).astype(long), bins=100)
#plt.hist(np.random.randint(low=-1e10, high=1e10, size=1000000), bins=100)
#plt.hist(np.random.poisson(lam=2, size=1000000), bins=13)
#plt.hist(np.random.exponential(scale=1e10, size=1000000).astype(long), bins=100)

plt.show()
```

<details>
  <summary>uniform</summary>
  
 uniform
  
</details>

<details>
  <summary>poisson right skewed</summary>
  
Poisson
  
</details>

<details>
  <summary>normal</summary>
  
normal
  
</details>

<details>
  <summary> exponential </summary>
  
exponential

</details>

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
What do you think of generating the data ad-hoc like it is done in https://github.com/crate/crate-benchmarks/blob/a64b7e89dadb02f6d93c7778cc188dae2c0fd75f/specs/memory_pressure/hll_high.toml#L6 ?

Would keep the repo size smaller. How long does it take to generate the data?

**Comment by BaurzhanSakhariev** [comment]
> Would keep the repo size smaller. How long does it take to generate the data?

Good idea, will try it out - it's about 5-10 sec for 1 million records

**Comment by mfussenegger** [comment]
> Good idea, will try it out - it's about 5-10 sec for 1 million records.

I think that's fast enough to generate ad-hoc instead of checking in.

**Comment by BaurzhanSakhariev** [comment]
Done in https://github.com/crate/crate-benchmarks/pull/249/commits/3ba11c67171728f79d23bfbdd6a7f34be9103075
Did I understand correctly, that in ad-hoc generation we don't use gzip but rather script output gets directly piped to cr8?

**Review by mfussenegger — APPROVED** [review]

**Comment by mfussenegger** [comment]
> Did I understand correctly, that in ad-hoc generation we don't use gzip but rather script output gets directly piped to cr8?

yes

**Pull request merged**
