### PR TITLE
Update bad_partitions.py

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
From time to time issues with the message 
>cr8 insert-json --hosts https://crate-production.aks1.westeurope.azure.cratedb.net:4200 --table benchmark.dev_cluster
SqlException: RelationAlreadyExists[Relation 'doc.tp' already exists.]

pop up and then closed automatically.

Resolves https://github.com/crate/crate-alerts/issues/119
[Others](https://github.com/search?p=3&q=org%3Acrate+%22Relation+%27doc.tp%27+already+exists.%22&type=Issues)

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by BaurzhanSakhariev** [comment]
We have `drop table` on teardown but perhaps there exists another script creating table with the same name on the dev cluster?

**Review by mfussenegger — COMMENTED** [review]
This looks as if it is just working around a symptom and not really fixing the root cause. 

If the test scenario doesn't create the table, it means it will no longer create partitions, which means the whole test doesn't do anymore what it is supposed to do.


I think a better mitigation would be to change the benchmark job to first run the teardown for all specs to ensure any artifcats from previous (maybe failed)  runs or from ad-hoc experiments are gone. It is a shared cluster, so there is always the chance that somebody creates tables that overlap with the ones we use in the benchmarks.

**Comment by BaurzhanSakhariev** [comment]
> to first run the teardown for all specs 

Would adding teardown statement to all setups be acceptable approach?

Like  replacing 
```
setup=Instructions(statements=[CREATE_TABLE]),
teardown=Instructions(statements=["DROP TABLE tp"]),
queries=_queries(),
```
with 
```
setup=Instructions(statements=["DROP TABLE IF EXISTS tp", "CREATE_TABLE"]),
teardown=Instructions(statements=["DROP TABLE tp"]),
queries=_queries(),
```

And then repeat this for all steps - but take corresponding teardown for each spec. 

Otherwise I can imagine only patching cr8 itself by adding some flag like "run-tear-down-before-spec"

**Comment by BaurzhanSakhariev** [comment]
> first run the teardown for all specs

Thx for the comment, only after that checked `cr8 run-spec` args carefully - I utilised action argument in https://github.com/crate/jenkins-dsl/pull/1001/

**Pull request closed without merging**
